/// One row per survey response, linked to the request it rates by case number.
table Survey

	/// Survey responses in the current filter.
	measure Responses = COUNTROWS ( Survey )
		formatString: #,0
		displayFolder: Feedback

	measure 'Responses (card)' = COALESCE ( [Responses], 0 )
		formatString: #,0
		displayFolder: Cards
		isHidden

	measure 'Written comments' = CALCULATE ( COUNTROWS ( Survey ), KEEPFILTERS ( Survey[Written] = "Yes" ) )
		formatString: #,0
		displayFolder: Feedback

	measure 'Written comments (card)' = COALESCE ( [Written comments], 0 )
		formatString: #,0
		displayFolder: Cards
		isHidden

	/// Written comments other than "N/A" and similar non-answers.
	measure 'Substantive comments' = CALCULATE ( COUNTROWS ( Survey ), KEEPFILTERS ( Survey[Substantive] = "Yes" ) )
		formatString: #,0
		displayFolder: Feedback

	measure 'Substantive comments (card)' = COALESCE ( [Substantive comments], 0 )
		formatString: #,0
		displayFolder: Cards
		isHidden

	/// Responses coded to an improvement theme.
	measure 'Improvement opportunities' = CALCULATE ( COUNTROWS ( Survey ), KEEPFILTERS ( NOT ISBLANK ( Survey[Improvement theme] ) ) )
		formatString: #,0
		displayFolder: Feedback

	measure 'Improvement opportunities (card)' = COALESCE ( [Improvement opportunities], 0 )
		formatString: #,0
		displayFolder: Cards
		isHidden

	/// Responses about requests that were cancelled, misassigned or could not be evaluated.
	measure 'Data-quality flags' = CALCULATE ( COUNTROWS ( Survey ), KEEPFILTERS ( NOT ISBLANK ( Survey[Data quality flag] ) ) )
		formatString: #,0
		displayFolder: Feedback

	measure 'Data-quality flags (card)' = COALESCE ( [Data-quality flags], 0 )
		formatString: #,0
		displayFolder: Cards
		isHidden

	measure 'Offices responding' = DISTINCTCOUNTNOBLANK ( Survey[Survey office] )
		formatString: #,0
		displayFolder: Feedback

	measure 'All responses' = CALCULATE ( [Responses], REMOVEFILTERS ( DimType ), REMOVEFILTERS ( DimPractice ), REMOVEFILTERS ( DimOffer ), REMOVEFILTERS ( DimOffice ) )
		formatString: #,0
		displayFolder: Feedback

	measure 'Showing responses' = "Showing " & FORMAT ( [Responses (card)], "#,0" ) & " survey responses  (" & FORMAT ( DIVIDE ( [Responses (card)], [All responses] ), "0%" ) & " of all)"
		displayFolder: Text

	measure 'Feedback filter summary' =
			VAR typ = IF ( ISFILTERED ( DimType[Request type] ), CONCATENATEX ( VALUES ( DimType[Request type] ), DimType[Request type], ", " ) & " requests", "All requests" )
			VAR reg = IF ( ISFILTERED ( DimOffice[Region] ), CONCATENATEX ( VALUES ( DimOffice[Region] ), DimOffice[Region], ", " ), "all regions" )
			VAR pra = IF ( ISFILTERED ( DimPractice[Practice] ), "  ·  " & CONCATENATEX ( VALUES ( DimPractice[Practice] ), DimPractice[Practice], ", " ) )
			VAR off = IF ( ISFILTERED ( DimOffice[Office] ), "  ·  " & CONCATENATEX ( VALUES ( DimOffice[Office] ), DimOffice[Office], ", " ) )
			VAR ofr = IF ( ISFILTERED ( DimOffer[Programme offer] ), "  ·  " & CONCATENATEX ( VALUES ( DimOffer[Programme offer] ), DimOffer[Programme offer], ", " ) )
			VAR anyFilter = ISFILTERED ( DimType[Request type] ) || ISFILTERED ( DimOffice[Region] ) || ISFILTERED ( DimPractice[Practice] )
			    || ISFILTERED ( DimOffice[Office] ) || ISFILTERED ( DimOffer[Programme offer] )
			RETURN
			    IF ( anyFilter, typ & "  ·  " & reg & pra & off & ofr, "All survey responses — every request type, region & practice" )
		displayFolder: Text

	measure 'Responses sub' = "across " & FORMAT ( [Offices responding], "#,0" ) & " country offices"
		displayFolder: Text

	measure 'Written sub' = FORMAT ( DIVIDE ( [Written comments (card)], [Responses] ), "0%" ) & " of respondents wrote something"
		displayFolder: Text

	measure 'Improvement sub' = IF ( [Written comments (card)] > 0, FORMAT ( DIVIDE ( [Improvement opportunities (card)], [Written comments] ), "0%" ) & " of comments name something to fix", "no written comments" )
		displayFolder: Text

	measure 'Flags sub' =
			VAR f = CALCULATETABLE ( VALUES ( SurveyThemes[Theme] ), SurveyThemes[Kind] = "Data-quality flag" )
			RETURN IF ( COUNTROWS ( f ) > 0, CONCATENATEX ( f, LOWER ( SurveyThemes[Theme] ), ", " ), "none for this selection" )
		displayFolder: Text

	/// Overall satisfaction, 1–5 (unrated answers such as "Too early to say" are left out).
	measure 'Average satisfaction' = AVERAGE ( Survey[Satisfaction] )
		formatString: 0.00
		displayFolder: Feedback

	measure 'Satisfaction stars' =
			VAR v = [Average satisfaction]
			VAR k = ROUND ( v, 0 )
			RETURN IF ( ISBLANK ( v ), "not rated", REPT ( "★", k ) & REPT ( "☆", 5 - k ) )
		displayFolder: Text

	/// Quality of the assistance, 1–5 (unrated answers such as "Too early to say" are left out).
	measure 'Average quality' = AVERAGE ( Survey[Quality] )
		formatString: 0.00
		displayFolder: Feedback

	measure 'Quality stars' =
			VAR v = [Average quality]
			VAR k = ROUND ( v, 0 )
			RETURN IF ( ISBLANK ( v ), "not rated", REPT ( "★", k ) & REPT ( "☆", 5 - k ) )
		displayFolder: Text

	/// Timeliness, 1–5 (unrated answers such as "Too early to say" are left out).
	measure 'Average timeliness' = AVERAGE ( Survey[Timeliness] )
		formatString: 0.00
		displayFolder: Feedback

	measure 'Timeliness stars' =
			VAR v = [Average timeliness]
			VAR k = ROUND ( v, 0 )
			RETURN IF ( ISBLANK ( v ), "not rated", REPT ( "★", k ) & REPT ( "☆", 5 - k ) )
		displayFolder: Text

	/// Would recommend, 0–10.
	measure 'Average recommend' = AVERAGE ( Survey[Recommend] )
		formatString: 0.0
		displayFolder: Feedback

	measure 'Recommend stars' =
			VAR v = [Average recommend] / 2
			VAR k = ROUND ( v, 0 )
			RETURN IF ( ISBLANK ( v ), "not rated", REPT ( "★", k ) & REPT ( "☆", 5 - k ) )
		displayFolder: Text

	measure 'Rated responses' = COUNT ( Survey[Satisfaction] )
		formatString: #,0
		displayFolder: Feedback

	measure 'Rated sub' = FORMAT ( [Rated responses] + 0, "#,0" ) & " rated responses"
		displayFolder: Text

	/// Map bubble colour: 4.5+ dark green, 4.0–4.5 green, 3.5–4.0 amber, below 3.5 red, grey = no rating.
	measure 'Rating colour' =
			VAR v = [Average satisfaction]
			RETURN
			    SWITCH ( TRUE (), ISBLANK ( v ), "#AEBCC7", v >= 4.5, "#2E7D5B", v >= 4, "#5FA98A", v >= 3.5, "#E0A21E", "#C0453F" )
		displayFolder: Text

	measure 'Map longitude' = AVERAGE ( Survey[Longitude] )
		formatString: 0.00
		displayFolder: Feedback
		isHidden

	measure 'Map latitude' = AVERAGE ( Survey[Latitude] )
		formatString: 0.00
		displayFolder: Feedback
		isHidden

	/// Respondents whose comment named at least one thing that worked.
	measure 'Comments with positive feedback' = CALCULATE ( COUNTROWS ( Survey ), KEEPFILTERS ( Survey[Has positive feedback] = "Yes" ) )
		formatString: #,0
		displayFolder: Feedback

	measure 'Comments with positive feedback (card)' = COALESCE ( [Comments with positive feedback], 0 )
		formatString: #,0
		displayFolder: Cards
		isHidden

	measure 'Type line' =
			VAR r = CALCULATE ( [Responses], Survey[Request type] = "Routine" ) + 0
			VAR b = CALCULATE ( [Responses], Survey[Request type] = "Big Ticket" ) + 0
			VAR u = CALCULATE ( [Responses], Survey[Request type] = "Unclassified" ) + 0
			RETURN
			    FORMAT ( [Responses (card)], "#,0" ) & " responses from " & FORMAT ( [Offices responding], "#,0" ) & " country offices — "
			        & FORMAT ( r, "#,0" ) & " Routine, " & FORMAT ( b, "#,0" ) & " Big Ticket"
			        & IF ( u > 0, ", " & FORMAT ( u, "#,0" ) & " not matched to a request" ) & ". "
			        & "Each response is matched to the request it rates by case number, so the slicers above apply here."
		displayFolder: Text

	measure 'Data note' =
			VAR f = [Data-quality flags (card)]
			VAR matched = CALCULATE ( [Responses], Survey[Matched to request] = "Yes", REMOVEFILTERS ( DimType ), REMOVEFILTERS ( DimPractice ), REMOVEFILTERS ( DimOffer ), REMOVEFILTERS ( DimOffice ) )
			RETURN
			    IF ( f > 0,
			        FORMAT ( f, "#,0" ) & " of the " & FORMAT ( [Responses (card)], "#,0" ) & " responses describe requests that were "
			            & [Flags sub] & ". They are counted separately and excluded from the themes above: reading them as dissatisfaction "
			            & "would understate the service, and they belong in the data-quality workstream rather than in service feedback. ",
			        "" )
			    & "Responses are matched to requests on the case number (CS…) the respondent quoted. " & FORMAT ( matched, "#,0" )
			    & " of the " & FORMAT ( [All responses], "#,0" ) & " responses match; the rest keep the office they reported and count as "
			    & """not matched to a request"", so they drop out once a type, practice or programme offer is chosen."
		displayFolder: Text

	column 'Response ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Response ID

	/// The office as the respondent named it.
	column 'Survey office'
		dataType: string
		summarizeBy: none
		sourceColumn: Survey office

	column 'Case number'
		dataType: string
		summarizeBy: none
		sourceColumn: Case number

	column 'Request ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Request ID

	/// Yes / No
	column 'Matched to request'
		dataType: string
		summarizeBy: none
		sourceColumn: Matched to request

	column 'Request type'
		dataType: string
		summarizeBy: none
		sourceColumn: Request type

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

	column Office
		dataType: string
		summarizeBy: none
		sourceColumn: Office

	column Practice
		dataType: string
		summarizeBy: none
		sourceColumn: Practice

	column 'Programme offer'
		dataType: string
		summarizeBy: none
		sourceColumn: Programme offer

	column Comment
		dataType: string
		summarizeBy: none
		sourceColumn: Comment

	/// Yes / No
	column Written
		dataType: string
		summarizeBy: none
		sourceColumn: Written

	/// Yes / No: written, and not "N/A" or similar.
	column Substantive
		dataType: string
		summarizeBy: none
		sourceColumn: Substantive

	/// Yes / No
	column 'Has positive feedback'
		dataType: string
		summarizeBy: none
		sourceColumn: Has positive feedback

	column 'Positive themes'
		dataType: string
		summarizeBy: none
		sourceColumn: Positive themes

	column 'Improvement theme'
		dataType: string
		summarizeBy: none
		sourceColumn: Improvement theme

	column 'Data quality flag'
		dataType: string
		summarizeBy: none
		sourceColumn: Data quality flag

	column Themes
		dataType: string
		summarizeBy: none
		sourceColumn: Themes

	/// Satisfaction as stars.
	column Rating
		dataType: string
		summarizeBy: none
		sourceColumn: Rating

	column Satisfaction
		dataType: int64
		formatString: 0
		summarizeBy: average
		sourceColumn: Satisfaction

	column Quality
		dataType: int64
		formatString: 0
		summarizeBy: average
		sourceColumn: Quality

	column Timeliness
		dataType: int64
		formatString: 0
		summarizeBy: average
		sourceColumn: Timeliness

	column Contribution
		dataType: int64
		formatString: 0
		summarizeBy: average
		sourceColumn: Contribution

	column Recommend
		dataType: double
		summarizeBy: average
		sourceColumn: Recommend

	column Longitude
		dataType: double
		dataCategory: Longitude
		summarizeBy: average
		sourceColumn: Longitude

	column Latitude
		dataType: double
		dataCategory: Latitude
		summarizeBy: average
		sourceColumn: Latitude

	column 'Featured quote'
		dataType: string
		summarizeBy: none
		sourceColumn: Featured quote

	column 'Featured quote tone'
		dataType: string
		summarizeBy: none
		sourceColumn: Featured quote tone

	partition Survey = m
		mode: import
		source =
				// One row per survey response, linked to the request it rates by case number (CS…).
				// Port of scripts/extract_survey.py + app/src/lib/feedback.ts.
				let
				    Book = Excel.Workbook(fnReadFile(SurveyWorkbookPath), [UseHeaders = false, DelayTypes = true, InferSheetDimensions = true]),
				    Merged = fnSurveySheet(Book, "Merged data"),
				    // the merge blanks some open-text answers, so the raw sheet is the authority on what was written
				    Responses = fnSurveySheet(Book, "Response data"),
				    RawComments = Table.Buffer(Table.FromRows(
				        List.Transform(Table.ToRecords(Responses), each {fnText([ID]), fnText(Record.FieldOrDefault(_, "Open comment", null))}),
				        {"ID", "Raw comment"})),
				    Scales = [
				        Satisfaction = [#"Very dissatisfied" = 1, Dissatisfied = 2, #"Neither satisfied nor dissatisfied" = 3, Satisfied = 4, #"Very satisfied" = 5],
				        Quality = [Poor = 1, Fair = 2, Good = 3, #"Very Good" = 4, Excellent = 5],
				        Timeliness = [#"Much too late" = 1, #"Too late" = 2, Acceptable = 3, Timely = 4, #"Very Timely" = 5],
				        Contribution = [#"No Contribution" = 1, #"Limited Contribution" = 2, #"Moderate Contribution" = 3, #"Significant Contribution" = 4, #"Very Significant Contribution" = 5]
				    ],
				    Score = (scale as text, label as text) as nullable number => Record.FieldOrDefault(Record.Field(Scales, scale), label, null),
				    NonSubstantive = {"", "n/a", "na", "no comment", "no comments", "none", "nil", ".", "-", "..", "..."},
				    Cases = Table.Buffer(Table.SelectColumns(RawRequestsAll, {"Number", "Request ID", "Request Type", "Office/Division", "Global Practice and Cross Sectoral Teams", "Primary Programme Offer"})),

				    Rows = List.Transform(Table.ToRecords(Merged), (r) =>
				        let
				            Id = fnText(r[ID]),
				            CaseNo = fnText(Record.FieldOrDefault(r, "TA Case Number", null)),
				            RawPos = List.PositionOf(RawComments[ID], Id),
				            RawBody = if RawPos >= 0 then RawComments[Raw comment]{RawPos} else "",
				            Body = if RawBody <> "" then RawBody else fnText(Record.FieldOrDefault(r, "Open comment", null)),
				            Written = Body <> "",
				            Substantive = Written and not List.Contains(NonSubstantive, Text.TrimEnd(Text.Lower(Text.Trim(Body)), {".", "!", "?"})),
				            ManualPos = List.PositionOf(ManualCoding[ID], Id),
				            Manual = if ManualPos >= 0 then ManualCoding{ManualPos} else null,
				            Positive = if Manual <> null then Manual[Positive] else fnText(Record.FieldOrDefault(r, "Positive Themes", null)),
				            Improvement = if Manual <> null then Manual[Improvement] else fnText(Record.FieldOrDefault(r, "Improvement Theme", null)),
				            Flag = if Manual <> null then Manual[Flag] else fnText(Record.FieldOrDefault(r, "Data-quality Flag", null)),
				            SatLabel = fnText(Record.FieldOrDefault(r, "Satisfaction", null)),
				            FixPos = List.PositionOf(SatisfactionCorrections[Case number], CaseNo),
				            SatFixed = if FixPos >= 0 and SatLabel = SatisfactionCorrections[From]{FixPos} then SatisfactionCorrections[To]{FixPos} else SatLabel,
				            Rec = try Number.From(fnText(Record.FieldOrDefault(r, "Recommend 0–10", null))) otherwise null,
				            CasePos = if CaseNo = "" then -1 else List.PositionOf(Cases[Number], CaseNo, Occurrence.Last),
				            Case = if CasePos >= 0 then Cases{CasePos} else null,
				            CaseOffice = if Case <> null then Case[#"Office/Division"] else ""
				        in
				            [
				                Response ID = Id,
				                Survey office raw = fnText(Record.FieldOrDefault(r, "Country Office", null)),
				                Case number = CaseNo,
				                Request ID = if Case <> null then Case[Request ID] else null,
				                Office raw = if CaseOffice <> "" then CaseOffice else fnText(Record.FieldOrDefault(r, "Country Office", null)),
				                Request type = if Case = null then "Unclassified" else (let t = fnMapType(Case[Request Type]) in if t = "" then "Unclassified" else t),
				                Practice = if Case = null then null else fnMapPractice(Case[Global Practice and Cross Sectoral Teams]),
				                Programme offer = if Case = null then null else fnMapOffer(Case[Primary Programme Offer]),
				                Comment = Body,
				                Written = if Written then "Yes" else "No",
				                Substantive = if Substantive then "Yes" else "No",
				                Positive themes = Positive,
				                Improvement theme = if Improvement = "" then null else Improvement,
				                Data quality flag = if Flag = "" then null else Flag,
				                Satisfaction = Score("Satisfaction", SatFixed),
				                Quality = Score("Quality", fnText(Record.FieldOrDefault(r, "Quality", null))),
				                Timeliness = Score("Timeliness", fnText(Record.FieldOrDefault(r, "Timeliness", null))),
				                Contribution = Score("Contribution", fnText(Record.FieldOrDefault(r, "Contribution", null))),
				                Recommend = Rec
				            ]
				    ),
				    Table0 = Table.FromRecords(Rows),
				    Kept = Table.SelectRows(Table0, each not List.Contains(ExcludedResponses, [Response ID])),
				    WithPlace = fnMapOffices(Kept, "Office raw"),
				    // the office as respondents named it keys the map; HQ divisions get their readable name
				    SurveyOffice = Table.AddColumn(WithPlace, "Survey office", each
				        let p = List.PositionOf(HqOffices[Raw], [Survey office raw]) in if p >= 0 then HqOffices[Office]{p} else [Survey office raw], type text),
				    WithCoords = Table.AddColumn(SurveyOffice, "xy", each
				        let p = List.PositionOf(OfficeCoords[Office], [Survey office raw]) in if p >= 0 then OfficeCoords{p} else null),
				    Lon = Table.AddColumn(WithCoords, "Longitude", each if [xy] = null then null else [xy][Longitude], type nullable number),
				    Lat = Table.AddColumn(Lon, "Latitude", each if [xy] = null then null else [xy][Latitude], type nullable number),
				    Featured = Table.AddColumn(Lat, "fq", each let p = List.PositionOf(FeaturedQuotes[ID], [Response ID]) in if p >= 0 then FeaturedQuotes{p} else null),
				    Quote = Table.AddColumn(Featured, "Featured quote", each if [fq] = null then null else [fq][Quote], type nullable text),
				    QuoteTone = Table.AddColumn(Quote, "Featured quote tone", each if [fq] = null then null else [fq][Tone], type nullable text),
				    HasPositive = Table.AddColumn(QuoteTone, "Has positive feedback", each if [Positive themes] <> "" then "Yes" else "No", type text),
				    Matched = Table.AddColumn(HasPositive, "Matched to request", each if [Request ID] <> null then "Yes" else "No", type text),
				    Stars = Table.AddColumn(Matched, "Rating", each if [Satisfaction] = null then "not rated" else Text.Repeat("★", [Satisfaction]) & Text.Repeat("☆", 5 - [Satisfaction]), type text),
				    Themes = Table.AddColumn(Stars, "Themes", each Text.Combine(List.Select(
				        List.Transform(Text.Split([Positive themes], ";"), Text.Trim) & {[Improvement theme], [Data quality flag]},
				        (t) => t <> null and t <> ""), " · "), type text),
				    Selected = Table.SelectColumns(Themes, {
				        "Response ID", "Survey office", "Case number", "Request ID", "Matched to request", "Request type", "Region", "Office",
				        "Practice", "Programme offer", "Comment", "Written", "Substantive", "Has positive feedback", "Positive themes",
				        "Improvement theme", "Data quality flag", "Themes", "Rating", "Satisfaction", "Quality", "Timeliness", "Contribution", "Recommend",
				        "Longitude", "Latitude", "Featured quote", "Featured quote tone"}),
				    Keys = Table.TransformColumns(Selected, List.Transform({"Office", "Practice", "Programme offer"},
				        (c) => {c, each if _ = "" then null else _, type nullable text})),
				    Typed = Table.TransformColumnTypes(Keys, {
				        {"Response ID", type text}, {"Case number", type text}, {"Request ID", type text}, {"Request type", type text},
				        {"Region", type text}, {"Comment", type text}, {"Written", type text}, {"Substantive", type text},
				        {"Positive themes", type text}, {"Improvement theme", type text}, {"Data quality flag", type text},
				        {"Satisfaction", Int64.Type}, {"Quality", Int64.Type}, {"Timeliness", Int64.Type}, {"Contribution", Int64.Type},
				        {"Recommend", type number}})
				in
				    Typed
